name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-python@v2
    - name: install dependencies
      run:
        python -m pip install --upgrade pip
        